services:
  mysql:
    image: mariadb:11.4
    command:
    - mariadbd
    - --character-set-server=utf8mb4
    environment:
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test:
      - CMD
      - /usr/local/bin/healthcheck.sh
      - --su-mysql
      - --connect
      - --innodb_initialized
      start_period: 1m
      start_interval: 10s
      interval: 1m
      timeout: 5s
      retries: 3
  openemr:
    profiles:
    - prod
    build:
      context: ${DOCKER_CONTEXT_PATH}
    ports:
    - 8080:80
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      MANUAL_SETUP: 'yes'
      MYSQL_HOST: mysql
      MYSQL_PASS: openemr
      MYSQL_ROOT_PASS: root
      MYSQL_USER: openemr
      OE_PASS: pass
      OE_USER: admin
    healthcheck:
      test:
      - CMD
      - curl
      - -fsSLo/dev/null
      - http://localhost/
      start_period: 10m
      start_interval: 10s
      interval: 1m
      timeout: 5s
      retries: 3
  openemr-flex:
    extends:
      service: openemr
    profiles: !override
    - flex
    volumes:
    - ../../openemr:/var/www/localhost/htdocs/openemr
